# Generated by Django 2.2.10 on 2020-03-29 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('currency', '0002_auto_20200312_1758'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rate',
            name='source',
            field=models.PositiveSmallIntegerField(choices=[(1, 'PrivatBank'), (2, 'MonoBank'), (3, 'Vkurse'), (4, 'MTBbank'), (5, 'AlphaBank'), (6, 'ComcordBank')]),
        ),
    ]
